### ISSUE TITLE
Empty vclock for first entry in history table

### ISSUE THREAD

**Issue by cvlong** [CloverHealth/temporal-sqlalchemy#21]
Some temporal history tables have vclock values that are 'empty' for the first history entry.

1. Create a new activity_1
2. Create a new instance of a model with boolean property set to False tied to activity_1
3. Add instance to session & flush
4. Create activity_2
5. Enter into a clock tick context for the instance using activity_2
6. Change boolean property on instance to True
7. Flush the session

Actual output:
vclock activity_1 = empty
vclock activity_2 = [1,)

Expected output:
vclock activity_1 = [1, 2)
vclock activity_2 = [2,)

**Comment by bijanvakili** [comment]
Fix implemented with `strict_mode` flag in PR #24
