### ISSUE TITLE
Remove redundant `effective` column from history tables

### ISSUE THREAD

**Issue by bijanvakili** [CloverHealth/temporal-sqlalchemy#27]
The `effective` column on the history table is redundant. The clock table already contains `timestamps` for all ticks.  The `vclock` column on the history tables is sufficient to indicate the time range for a property change.

The `effective` column should therefore be removed from the history table.

**Comment by dave-clover** [comment]
I agree, but that change would cause a lot of breakages downstream.  And would make querying much harder.

**Comment by bijanvakili** [comment]
Yes, it would be a breaking a change.

A potential solution to avoid complex querying would be to optionally load the timestamp ranges in python.  If OLAP queries become complex, one could always implement database views for common history tables.

**Comment by multigl** [comment]
turns out the effective ranges have been helpful in reconstituting history, we should keep them for the time being.
